mona:
  enabled: true              # 모드 ON → 연결되면 모나로 명령 전송, 아니면 시뮬레이터로 폴백
  udp_port: 9999
  g_interval_sec: 0.00       # G 전송 주기(초). 0.05~0.20 권장
  deadband_deg: 0.0            # 작은 회전 지령 무시
  deadband_mm: 0.0            # 작은 전진 지령 무시
  arrive_threshold_mm: 40.0     # 도착 거리(mm) - (BT 도착은 px 기준, G 보정은 mm/deg 기준으로도 병행 가능)
  arrive_heading_deg: 360.0       # 도착 헤딩(도)
  distance_scale: 0.95
  
  robots:
  - agent_id: 0
    host: 10.122.98.30   # MONA #1 IP
    port: 8080           # MONA #1 포트
  - agent_id: 1
    host: 10.122.98.217   # MONA #2 IP
    port: 8080           # MONA #2 포트
  - agent_id: 2
    host: 10.122.98.229   # MONA #2 IP
    port: 8080           # MONA #2 포트

#  robots:
#  - agent_id: 0
#    host: 192.168.0.54   # MONA #1 IP
#    port: 8080           # MONA #1 포트
#  - agent_id: 1
#    host: 192.168.0.53   # MONA #2 IP
#    port: 8080           # MONA #2 포트
#  - agent_id: 2
#    host: 192.168.0.52   # MONA #2 IP
#    port: 8080           # MONA #2 포트

scenario: 
  environment: scenarios.features.mona

# decision_making: # Case 1
#   plugin: plugins.grape.grape.GRAPE
#   GRAPE:
#     cost_weight_factor: 1.0
#     social_inhibition_factor: 100
#     initialize_partition: Distance # Options: None; Distance      
#     reinitialize_partition_on_completion: Distance # Options: None; Distance; 

decision_making: # Case 2
  plugin: plugins.cbba.cbba.CBBA
  CBBA:  
    max_tasks_per_agent: 5 
    task_reward_discount_factor: 0.999 
    winning_bid_cancel: True
    acceptable_empty_bundle_duration: 500 # sec

# decision_making: # Case 3
#   plugin: plugins.greedy.greedy.FirstClaimGreedy
#   FirstClaimGreedy:  
#     mode: MinDist  # Options: Random; MinDist; MaxUtil
#     weight_factor_cost: 10000.0 # Only used for `MaxUtil` mode
#     enforced_collaboration: False  


agents:
  behavior_tree_xml: default_bt.xml 
  quantity: 3
  locations:
    x_min: 0
    x_max: 1340
    y_min: 0
    y_max: 740
    non_overlap_radius: 0 
  max_speed: 0.25  
  max_accel: 0.05
  max_angular_speed: 0.25
  target_approaching_radius: 50
  work_rate: 1  # work rate for each agent (per 1.0/simulation.sampling_freq)
  communication_radius: 500 # 0 represents "global", meaning that each agent can access to the information of all the other agents
  situation_awareness_radius: 500 # 0 represents "global", meaning that each agent can access to the information of all the tasks
  random_exploration_duration: 1000.0 # sec

tasks:
  quantity: 0
  locations:
    x_min: 0
    x_max: 1340
    y_min: 0
    y_max: 740
    non_overlap_radius: 0
  threshold_done_by_arrival: 40.0
  amounts:  # Added amounts range for tasks
    min: 6.0
    max: 60.0      
  dynamic_task_generation:
    enabled: True
    interval_seconds: 2000
    max_generations: 3
    tasks_per_generation: 0

simulation:
  random_seed: 1  # Random seed (integer ≥ 1), or None to disable seeding
  sampling_freq: 25 
  speed_up_factor: 0 # 0 mean max booster; 1 means normal; 10 means 10-times faster
  max_simulation_time: 0 # 0 means no limit
  agent_track_size: 400  
  screen_width: 1340 
  screen_height: 740 
  gif_recording_fps: 0.05  
  task_visualisation_factor: 3  # visualization factor for tasks : 10 means converting 10 amount to 1 pixel
  profiling_mode: False
  rendering_mode: Screen  # Options: Screen; Terminal; None
  rendering_options: # Only works if `rendering_mode` is `Screen`
    agent_tail: True
    agent_communication_topology: True
    agent_situation_awareness_circle: False
    agent_id: True
    agent_work_done: True
    agent_assigned_task_id: True
    agent_path_to_assigned_tasks: True
    task_id: False
  saving_options:
    output_folder: output
    with_date_subfolder: True
    save_gif: False  # Only works if `rendering_mode` is `Screen`
    save_timewise_result_csv: True    
    save_agentwise_result_csv: True
    save_config_yaml: True
  bt_visualiser:
    enabled: True       # Set to True to enable BT visualisation, False to disable
    agent_id: 0         # ID of the agent whose behaviour tree will be visualised
